id: P04BBE7B7
initial_creation_type: input
source_metadata:
  title: Inscriptions Series
  language: pt
  description: 'A series of inscriptions (byang yig) including verso inscriptions
    (rgyab byang) and recto inscriptions (zhal byang) from thangka paintings and other
    works of art:'
  volume:
    dbfd1afb40b84015ad2083168241ad5c:
      title: Verso Inscription on an Image of the Pure Land of Great Bliss
      parent: Verso Inscriptions
created_at: '2022-03-01T03:59:17.115749'
last_modified_at: '2022-03-01T03:59:17.115752'
